---
- include_role:
    name: namespace
    tasks_from: create
  vars:
    name: "{{ sso_namespace }}"
    display_name: "{{ sso_namespace_display_name | default('Red Hat Single Sign-On')}}"
    monitor: true
    is_service: true

- name: "Ensure {{ rhsso_imagestream_name }} tag is present for redhat sso in openshift namespace"
  shell: oc tag --source=docker {{ rhsso_imagestream_image }} openshift/{{ rhsso_imagestream_name }}
  register: result
  until: result.stdout
  retries: 50
  delay: 1
  failed_when: not result.stdout
  changed_when: False

- name: "Ensure {{ rhsso_imagestream_name }} tag has an imported image in openshift namespace"
  shell: oc -n openshift import-image {{ rhsso_imagestream_name }}
  register: result
  until: result.stdout
  retries: 50
  delay: 1
  failed_when: not result.stdout
  changed_when: False

- name: "Create required objects"
  shell: "oc create -f {{ item }} -n {{ sso_namespace }}"
  with_items: "{{ rhsso_operator_resource_items }}"
  register: rhsso_operator_resources_result
  failed_when: rhsso_operator_resources_result.stderr != '' and 'AlreadyExists' not in rhsso_operator_resources_result.stderr