---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Expose vars
      include_vars: "../roles/rhsso/defaults/main.yml"
    -
      name: Install launcher SSO
      include_role:
        name: launcher
        tasks_from: provision-sso
      when: launcher
    -
      name: Install rhsso
      include_role:
        name: rhsso
        tasks_from: integreatly_install
      vars:
        rhsso_redirect_uri: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}"
        apps_redirect_uri: "{{ hostvars['EVAL_VARS']['eval_app_host'] }}"
        enable_threescale_wildcard_route: "{{ eval_threescale_enable_wildcard_route }}"
      tags: ['rhsso']
